### PR TITLE
Change version requirement for django

### LINKED ISSUE #35: django-admin setup fails with 'RemovedInDjango20Warning' import error
When running
```
DJANGO_SETTINGS_MODULE=cluster_settings django-admin setup
```
I get this error
```
ImportError: cannot import name 'RemovedInDjango20Warning'
```
from django_cassandra_engine. It seems that this module is trying to import 
 'RemovedInDjango20Warning' from django.utils.deprecation. In Django 2.0 (the one downloaded in the workload setup when using Python 3.6.3), django.utils.deprecation only has a 'RemovedInDjango21Warning' class, causing the import error.

Already opened an issue in the django_cassandra_engine Github: https://github.com/r4fek/django-cassandra-engine/issues/107

Until the official fix, the workaround would be to manually edit the file _venv/lib/python3.6/site-packages/django_cassandra_engine/models/django_field_methods.py_ and change every occurrence of
```
RemovedInDjango20Warning
```
with 
```
RemovedInDjango21Warning
```

### PR DESCRIPTION
**Pull request by florinpapa**
This fixes https://github.com/Instagram/django-workload/issues/35, solving the incompatibility between django and django_cassandra_engine.

### CODE REVIEW

**Comment by cooperlees** [comment]
Sure for now. I guess we'd eventually want to work with >=2.0.

**Comment by florinpapa** [comment]
Thanks for merging, this will allow the project to build for now. When the fix is available in django_cassandra_driver, we can remove the django<2.0 restriction.
